all:
	g++ -g src/RegisterPool.cpp \
        src/VCDMonitor.cpp \
        src/RegisterFile.cpp \
        src/Hivek.cpp \
        src/Framebuffer.cpp \
        src/MemoryHierarchy.cpp \
        hts.cpp -o hts -lSDL2

clean:
	rm -rf hts waves.vcd
