all:
	g++ src/RegisterPool.cpp \
        src/ControlSignals.cpp \
        src/DatapathSignals.cpp \
        src/Hivek.cpp \
        src/MemoryHierarchy.cpp \
        hts.cpp -o hts

clean:
	rm -rf hts waves.vcd
