all:
	g++ src/RegisterPool.cpp \
        src/VCDMonitor.cpp \
        src/RegisterFile.cpp \
        src/Hivek.cpp \
        src/MemoryHierarchy.cpp \
        hts.cpp -o hts

clean:
	rm -rf hts waves.vcd
